FROM golang:1.25-alpine AS builder

WORKDIR /app

# 禁用代理
ENV HTTP_PROXY=""
ENV HTTPS_PROXY=""
ENV http_proxy=""
ENV https_proxy=""
ENV GOPROXY=https://goproxy.cn,direct

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker/main.go

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/worker .
COPY --from=builder /app/configs/config.docker.yaml ./configs/config.yaml

CMD ["./worker"]
